pipeline:

  staging-publish-pg-dispatcher:
    image: plugins/docker
    repo: nossas/pg-dispatcher
    secrets: [ docker_username, docker_password ]
    tags:
      - ${DRONE_BRANCH/\//-}
    when:
      status: success
      branch: [hotfix/*, release/*, feature/*, support/*, develop]

  production-publish-pg-dispatcher:
    image: plugins/docker
    repo: nossas/pg-dispatcher
    secrets: [ docker_username, docker_password ]
    tags:
      - ${DRONE_TAG##v}
    when:
      status: success
      event: tag
